# Site settings
title: Patrick Sullivan
email: patsul12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My Personal Site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patsul12.github.io" # the base hostname & protocol for your site
twitter_username: patricksulliv11
github_username:  patsul12

# Build settings
markdown: kramdown
